In [1]:
import numpy as np
import pandas as pd

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно.

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [3]:
a.size

12

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [4]:
a1 = a.reshape(12, 1)
a1

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [5]:
a2 = a.reshape(2, 6)
a2

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [6]:
a3 = a.reshape(6, 2)
a3

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [7]:
a4 = a.reshape(3, 4)
a4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
a5 = a.reshape(4, 3)
a5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [9]:
a1.ndim == a2.ndim == a3.ndim == a4.ndim == a5.ndim == 2

True

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [10]:
a_1 = a.reshape(12, -1)
a_1

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [11]:
a_2 = a.reshape(2, -1)
a_2

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [12]:
a_3 = a.reshape(6, -1)
a_3

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [13]:
a_4 = a.reshape(-1, 4)
a_4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
a_5 = a.reshape(-1, 3)
a_5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [15]:
a_1.ndim == a_2.ndim == a_3.ndim == a_4.ndim == a_5.ndim == 2

True

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

*Массивы a1 и a_1 состоят из 12 строк и одного столбца и являются двумерными.*

In [16]:
a1.shape, a1.ndim

((12, 1), 2)

In [17]:
a_1.shape, a1.ndim

((12, 1), 2)

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [18]:
mu, sigma = 0, 1
arr = np.random.normal(mu, sigma, size=(3, 4))
arr

array([[ 1.28576286, -0.8887186 , -0.08156866, -0.8577839 ],
       [-1.07353711, -1.99783579,  0.7261657 , -0.5022084 ],
       [-1.84406122, -0.9325997 , -0.39559491,  1.97926735]])

In [19]:
arr1 = arr.flatten()
arr1

array([ 1.28576286, -0.8887186 , -0.08156866, -0.8577839 , -1.07353711,
       -1.99783579,  0.7261657 , -0.5022084 , -1.84406122, -0.9325997 ,
       -0.39559491,  1.97926735])

In [20]:
arr.size == arr1.size

True

In [21]:
arr.ndim, arr1.ndim

(2, 1)

In [22]:
my_arr = np.random.standard_normal(size=(3, 4))
my_arr

array([[-7.09223531e-01,  9.59982306e-01,  1.55075804e+00,
        -4.00972301e-01],
       [-1.08311866e-03,  4.44003392e-01,  1.68495316e+00,
         8.60632833e-01],
       [-4.58008175e-01, -7.47522660e-01,  9.17237293e-01,
         6.54146844e-01]])

In [23]:
my_arr_2 = np.random.randn(3, 4)
my_arr_2

array([[ 0.66703722, -0.74047918, -0.20606911,  0.00473783],
       [ 0.22045861,  0.60034646, -2.40368514,  1.07942009],
       [-0.20638186,  0.97505133,  0.70377419,  0.60025871]])

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [24]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [25]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [26]:
a.size == b.size

True

In [27]:
a.ndim == b.ndim

False

In [28]:
b.shape

(1, 10)

*Массив a является одномерным, массив b - двумерным.*

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [29]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [30]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
a.shape[0] > 1

True

In [32]:
b.shape[0] - a.shape[0] == 1

True

In [33]:
a.ndim == b.ndim == 2

True

In [34]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
v.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [36]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [39]:
B = A @ At
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

*Матрица B имеет размер 4 х 4. Обратную матрицу вычислить невозможно, поскольку матрица B является вырожденной, т.е. ее определитель равен 0.*

In [40]:
B.shape

(4, 4)

In [41]:
B_det = np.linalg.det(B)
B_det

0.0

10. Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.

In [42]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [43]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [44]:
C = c.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [45]:
D = C*10 + B
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [46]:
D_det = np.linalg.det(D)
D_det

-28511999.999999944

In [47]:
D_rank = np.linalg.matrix_rank(D)
D_rank

4

In [48]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [49]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [50]:
np.all(1 or 0 in D_inv)

True

In [51]:
indices_1 = np.where(D_inv == 1)
indices_0 = np.where(D_inv == 0)

In [52]:
E = np.zeros([4, 4])

In [53]:
E[indices_1] = B[indices_1]
E[indices_0] = C[indices_0]
E

array([[  5.,  14.,  23.,  14.],
       [ 10.,   7.,  12., 122.],
       [  6.,   9.,   2., 212.],
       [ 32.,  10., 212.,   4.]])